groups:

  - name: turrets
    frame: torso_lift_link
    spheres: t0 t1 t2 t3
  - name: base
    frame: base_link
    spheres: b0 b1 b2 b3 b4 b6 b7 b8 b9
  - name: torso_upper
    frame: torso_lift_link
    spheres: s1 s2 s3 s4 s18 s19
  - name: torso_lower
    frame: base_link
    spheres: s13 s14 s15 s16 s17
  - name: tilt_laser
    frame: torso_lift_link
    spheres: s7 s8 s11 s12
  - name: head
    frame: head_pan_link
    spheres: s9 s10
  - name: right_gripper
    frame: r_wrist_roll_link
    spheres: g0 g1 g2
  - name: left_gripper
    frame: l_wrist_roll_link
    spheres: g0 g1 g2
  - name: right_forearm
    frame: r_elbow_flex_link
    spheres: fa0 fa1
  - name: left_forearm
    frame: l_elbow_flex_link
    spheres: fa0 fa1

b0: {x: 0.2, y: -0.2, z: 0.1, radius: 0.2, priority: 4}
b1: {x: 0.2, y: 0.2, z: 0.1, radius: 0.2, priority: 3}
b2: {x: -0.2, y: -0.2, z: 0.1, radius: 0.2, priority: 1}
b3: {x: -0.2, y: 0.2, z: 0.1, radius: 0.2, priority: 1}
b4: {x: -0.0, y: 0.0, z: 0.1, radius: 0.2, priority: 1}
b5: {x: 0.26, y: 0.0, z: 0.25, radius: 0.08, priority: 1}
b6: {x: 0.0, y: 0.2, z: 0.1, radius: 0.2, priority: 1}
b7: {x: 0.0, y: -0.2, z: 0.1, radius: 0.2, priority: 1}
b8: {x: -0.2, y: 0.0, z: 0.1, radius: 0.2, priority: 1}
b9: {x: 0.2, y: 0.0, z: 0.125, radius: 0.2, priority: 1}
s1: {x: -0.20, y: 0.10, z: 0.16, radius: 0.14, priority: 1}
s2: {x: -0.20, y: -0.10, z: 0.16, radius: 0.14, priority: 1}
s3: {x: -0.20, y: 0.10, z: -0.04, radius: 0.14, priority: 1}
s4: {x: -0.20, y: -0.10, z: -0.04, radius: 0.14, priority: 1}
s5: {x: 0.25, y: 0.0, z: -0.01, radius: 0.06, priority: 3}
s6: {x: 0.32, y: 0.0, z: -0.01, radius: 0.06, priority: 3}
s7: {x: 0.1, y: 0.05, z: 0.23, radius: 0.08, priority: 1}
s8: {x: 0.1, y: -0.05, z: 0.23, radius: 0.08, priority: 1}
s9: {x: 0.05, y: 0.06, z: 0.08, radius: 0.18, priority: 1}
s10: {x: 0.05, y: -0.06, z: 0.08, radius: 0.18, priority: 1}
s11: {x: 0.06, y: 0.16, z: 0.23, radius: 0.08, priority: 1}
s12: {x: 0.06, y: -0.16, z: 0.23, radius: 0.08, priority: 1}
s13: {x: -0.20, y: 0.0, z: 0.38, radius: 0.17, priority: 1}
s14: {x: -0.25, y: 0.10, z: 0.35, radius: 0.14, priority: 1}
s15: {x: -0.25, y: -0.10, z: 0.35, radius: 0.14, priority: 1}
s16: {x: -0.25, y: 0.10, z: 0.55, radius: 0.14, priority: 1}
s17: {x: -0.25, y: -0.10, z: 0.55, radius: 0.14, priority: 1}
s18: {x: -0.20, y: 0.10, z: -0.26, radius: 0.14, priority: 1}
s19: {x: -0.20, y: -0.10, z: -0.26, radius: 0.14, priority: 1}
g0: {x: 0.08, y: 0.0, z: 0.00, radius: 0.07, priority: 1}
g1: {x: 0.14, y: 0.0, z: 0.00, radius: 0.07, priority: 5}
g2: {x: 0.2, y: 0.0, z: 0.00, radius: 0.03, priority: 5}
fa0: {x: 0.2, y: 0.005, z: 0.00, radius: 0.08, priority: 1}
fa1: {x: 0.3, y: -0.005, z: 0.00, radius: 0.08, priority: 1}
t0: {x: -0.00, y: -0.188, z: -0.4, radius: 0.15, priority: 1}
t1: {x: -0.00, y: 0.188, z: -0.4, radius: 0.15, priority: 1}
t2: {x: -0.00, y: -0.188, z: -0.28, radius: 0.15, priority: 1}
t3: {x: -0.00, y: 0.188, z: -0.28, radius: 0.15, priority: 1}

