collision_space:
  visualizations: true
  reference_frame: map
  resolution: 0.02
  use_collision_map_from_sensors: false

  # dimensions from Sushi project
  occupancy_grid:
    origin_x: -3.5
    origin_y: -1.2
    origin_z: 0.0
    size_x: 7.0
    size_y: 4.0
    size_z: 2.0

